### ISSUE TITLE
Front-end improvements

### ISSUE THREAD

**Issue by stojanov-igor** [UniversalDot/front-end#18]
- [x] Remove the events from the task page, and add the events to the Notification bell on the top right corner.
- [x] Adding tasks to the organization is not working. They are added to OrganizationalTasks, but they are not showing up in front end.
- [x] Create a button in MyOrganization to create new organizations.
- [x] Members are not displayed. We query applicantsToOrganization with parameter `vision`
- [x] Check why changes to DB for some actions don't show up immediately in App via web sockets, while for some actions do. For ex. createOrganization immediately shows the new org. in view, and updateOrganization does after a page refresh.

**Comment by slaveatanasov** [comment]
Done.

**Comment by stojanov-igor** [comment]
Great.
