### ISSUE TITLE
Convert DateTime object to UnixTime

### ISSUE THREAD

**Issue by stojanov-igor** [UniversalDot/front-end#29]
The blockchain Node understands UnixTime. In the front-end application, we have to expose a human readable, `DateTime` object which is then converted to Unix time to be stored on the chain.

The application should be able:

- [x] Read UnixTime and convert it to DateTime coming from the back-end
- [x] Write DateTime on the front-end and store it as UnixTime in the backend

Check if the template has appropriate dateTime component? 
If not implement custom solution of find some npm package off the shelf.

**Comment by slaveatanasov** [comment]
Done.

**Comment by stojanov-igor** [comment]
Great looks nice.. 

When we assign DateTime, in which zone is this assigned? 

I think we have to always convert from local timezone into UTC.
UTC is based on the mean solar time at the prime meridian running through Greenwich, UK.

I have created a new task for this: https://github.com/UniversalDot/front-end/issues/32

**Comment by stojanov-igor** [comment]
Closing this one. Looks nice.
