### ISSUE TITLE
Assess deploy via webhook

### ISSUE THREAD

**Issue by evilrobot-01** [UniversalDot/front-end#4]
The current hosting provider only allows deploys [via webhook](https://support.hostinger.com/en/articles/1583302-how-can-i-deploy-a-git-repository). Need to firstly check whether they provide a mechanism for builds and if not, use GitHub Actions to build and push to another branch, which Hostinger can then simply pull from in order to deploy the front-end

**Comment by evilrobot-01** [comment]
Something like [push-to-branch-action](https://github.com/moodiest/push-to-branch-action#when-pushed-to-master-push-publicsite-to-the-gh-pages-branch-on-the-same-repo) or [git-publish-subdir-action](https://github.com/s0/git-publish-subdir-action) could simplify the workflow.

**Comment by evilrobot-01** [comment]
@JosephKnecht-lab Are you happy to use the [push-git-subdirectory-as-branch](https://github.com/marketplace/actions/push-git-subdirectory-as-branch) action to push the build output to local branch? 

Sample workflow at https://github.com/UniversalDot/front-end/blob/4-assess-deploy-via-webhook/.github/workflows/deploy.yml

**Comment by stojanov-igor** [comment]
I think we can use the same approach we are using for our docs website..

This is the flow: 
1) Every merge to master triggers a build: https://github.com/UniversalDot/udot-wiki/blob/master/.github/workflows/deploy.yml
2) This build is pushed to external repository.  It should be https://github.com/UniversalDot/deployed-front-end (See how it works based on the docs: https://github.com/UniversalDot/universaldot.github.io) 
3) Hostinger check for changes to deployed-front-end repo and pushed changes to subdomain. 

@evilrobot-01 You can finish up the first 2 and I will configure Hostinger.

**Comment by evilrobot-01** [comment]
Would it not be cleaner to just use a branch within existing repository, so all self-contained?

Hostinger allows you to specify a branch when setting up the Git deployment.
________________________________

**Comment by stojanov-igor** [comment]
Lets try your solution. It seems cleaner..

**Comment by evilrobot-01** [comment]
Seems to have worked based on https://github.com/UniversalDot/front-end/actions/runs/2868910445, do you want to review the [hosting](https://github.com/UniversalDot/front-end/tree/hosting) branch contents and if happy, set up the webhook? 

If all successful then we can remove the `.circleci` integration

**Comment by stojanov-igor** [comment]
Added a webhook for auto deploy on push event. https://github.com/UniversalDot/front-end/settings/hooks/374370813 

The deployment happens at https://test.universaldot.me/ . 

Currently, we deploy on every push to `develop`, which is fine, but I think in the future, we would like to deploy from `master`. 
Also we need to change the build from using yarn to npm instead. We can do this in new task.

We can remove the circleci.

**Comment by evilrobot-01** [comment]
I'll update to use `npm` and remove `.circleci` now as easy changes. 

The only thing is that the deploy hook should be on the `hosting` branch as that is what is being updated by the GitHub Actions workflow?

**Comment by stojanov-igor** [comment]
> The only thing is that the deploy hook should be on the `hosting` branch as that is what is being updated by the GitHub Actions workflow?

Not sure what you are asking. I configured that all the static files that are deployed to `hosting` branch be pushed to Hostinger automatically.

**Comment by evilrobot-01** [comment]
Replacing `yarn` with `npm` brought up dependency issues so best tackled separately. `.circleci` removed and badge on readme replaced with GH Actions. Will remove issue branch from workflow and submit PR.
