### ISSUE TITLE
CI Failing

### ISSUE THREAD

**Issue by evilrobot-01** [UniversalDot/front-end#7]
Ci is unfortunately failing due to an issue introduced with last night's calendar PR merge: https://github.com/UniversalDot/front-end/runs/7877466517?check_suite_focus=true

```
Failed to compile.

TS7006: Parameter 'params' implicitly has an 'any' type.
    148 |               label="Start date"
    149 |               inputFormat="dd/MM/yyyy hh:mm a"
  > 150 |               renderInput={(params) => <TextField {...params} fullWidth />}
        |                             ^^^^^^
    151 |             />
    152 |           )}
    153 |         />
```

This can also be seen on the previous CircleCI run for the PR merge: https://app.circleci.com/pipelines/github/UniversalDot/front-end/77/workflows/eb5650da-4024-4591-b68d-a83fd9056067/jobs/111

**Comment by stojanov-igor** [comment]
I have fixed this in this pull request. https://github.com/UniversalDot/front-end/pull/8
